services:
  traefik-forward-auth:
    image: "thomseddon/traefik-forward-auth:latest"
    hostname: "traefik-forward-auth"
    secrets:
      - source: traefik-forward-auth-v8
        target: /config
    environment:
      - CONFIG=/config
      #- SECRET=secret # additional security measurement which we didn't deploy
      #- INSECURE_COOKIE=true # this we only need if we're running over http entrypoint
    command:
      - "--whitelist=${FORWARD_AUTH_USER_EMAIL1}"
      - "--whitelist=${FORWARD_AUTH_USER_EMAIL2}"
      - "--log-level=debug"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.auth.loadbalancer.server.port=4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth@docker"
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

networks:
  proxy:
    external: true
    name: proxy

secrets:
  traefik-forward-auth-v8:
    external: true
    name: traefik-forward-auth-v8
