services:
  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    hostname: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_NAME}`)"
      - "traefik.http.routers.whoami.tls.certresolver=cloudflare"
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
