services:
  whoami:
    image: "containous/whoami"
    hostname: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_NAME}`)"
      - "traefik.http.routers.whoami.tls.certresolver=cloudflare"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

networks:
  proxy:
    external: true
    name: proxy
