global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp-mail.outlook.com:587'
  smtp_from: 'alert.${DOMAIN_NAME}@outlook.com'
  smtp_auth_username: 'alert.${DOMAIN_NAME}@outlook.com'
  smtp_auth_password: "${ALERTMANAGER_PASS}"

# The root route on which each incoming alert enters.
route:
  group_by: ['...']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: team-X-mails

receivers:
- name: 'team-X-mails'
  email_configs:
  - to: '${ALERTS_USER_EMAIL}'
    send_resolved: true
